namespace AetherCompass.Core;

/// <summary>Reviewed patch data. Native completion coverage is independent from this content catalogue.</summary>
public static class ObjectiveCatalog
{
    public const string Patch = "7.56";
    public static readonly DateOnly VerifiedDate = new(2026, 9, 20);
    public const string Patch74 = "https://na.finalfantasyxiv.com/lodestone/topics/detail/06944d892fd98cc00b2a28ff77edbafa4f7eef54/";
    public const string Patch75 = "https://na.finalfantasyxiv.com/lodestone/topics/detail/07320affa7e0fcd9685afcbe54fbf55405b6d822/";
    public const string Patch755 = "https://na.finalfantasyxiv.com/lodestone/topics/detail/99b6bfb8ecac428c7d3bb37dcb84b52f1064320b/";
    public const string Patch756 = "https://na.finalfantasyxiv.com/lodestone/topics/detail/a8a526ad64db45c8ca8d1c7fdcce8a5eedaa18bc/";

    public static IReadOnlyList<ObjectiveDefinition> All { get; } = new ObjectiveDefinition[]
    {
        new() { Id="msq", Title="Avancer l'épopée de Dawntrail", Description="Terminer l'épopée encore disponible pour ouvrir les contenus de niveau 100. Les prérequis exacts restent ceux du journal de quêtes.", MinimumLevel=1, Minutes=20, Focus=ObjectiveFocus.Story, Priority=98, SourceUrls=[Patch75] },
        new() { Id="gear-review", Title="Améliorer les emplacements faibles", Description="Vérifier arme, accessoires et équipement du job actif ; comparer les échanges accessibles avant d'acheter. Le score ne remplace pas un calcul de statistiques ou de best-in-slot.", Minutes=5, Focus=ObjectiveFocus.Gearing, Repeatable=true, Priority=92, SourceUrls=[Patch74,Patch75] },
        new() { Id="gear-catchup", Title="Comparer les voies de rattrapage i750–770", Description="Comparer l'équipement Historia i750 contre des mémoquartz Mathematics chez Zircon à Solution Neuf, et le craft Courtly Lover i770. Vérifier budget, job, qualité et coûts avant tout échange ou achat ; aucun achat automatique.", Minutes=10, Focus=ObjectiveFocus.Gearing, RewardItemLevel=770, RequiredQuestKey="dawntrail", Repeatable=true, Priority=94, SourceUrls=["https://na.finalfantasyxiv.com/lodestone/playguide/db/item/bbe5d772aba/","https://na.finalfantasyxiv.com/lodestone/playguide/db/item/a6886528380/","https://na.finalfantasyxiv.com/lodestone/topics/detail/3c4910f373e497acd3428c37f6358e341e4cc06d/",Patch74] },
        Unlock("unlock-mistwake", "Débloquer Mistwake", "mistwake", 85, Patch74),
        Unlock("unlock-clyteum", "Débloquer The Clyteum", "clyteum", 83, Patch75),
        Unlock("unlock-heavyweight", "Débloquer Arcadion Heavyweight", "heavyweight", 80, Patch74),
        Unlock("unlock-windurst", "Débloquer Windurst: The Third Walk", "windurst", 79, Patch75),
        new() { Id="mistwake", Title="Rattrapage : Mistwake", Description="Donjon de niveau 100 : entrée i735, équipement i755. Utile tant que certains emplacements sont en retrait.", MinimumItemLevel=735, RewardItemLevel=755, RewardSlots=[GearSlotKind.Armor,GearSlotKind.Accessory], Minutes=25, Focus=ObjectiveFocus.Gearing, UnlockKey="mistwake", RequiredQuestKey="dawntrail", Priority=78, Repeatable=true, SourceUrls=[Patch74] },
        new() { Id="clyteum", Title="Rattrapage : The Clyteum", Description="Donjon de niveau 100 : entrée i750, équipement i765.", MinimumItemLevel=750, RewardItemLevel=765, RewardSlots=[GearSlotKind.Armor,GearSlotKind.Accessory], Minutes=25, Focus=ObjectiveFocus.Gearing, UnlockKey="clyteum", RequiredQuestKey="dawntrail", Priority=77, Repeatable=true, SourceUrls=[Patch75] },
        new() { Id="expert-roulette", Title="Bonus quotidien de la roulette expert", Description="Vérifier le bonus du jour et gagner des mémoquartz. Le bonus quotidien et le plafond hebdomadaire sont suivis séparément.", MinimumItemLevel=750, Minutes=25, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Daily, UnlockKey="expert", RequiredQuestKey="dawntrail", Priority=75, SourceUrls=[Patch75] },
        new() { Id="mnemonics-cap", Title="Avancer le plafond de mémoquartz mnémoniques", Description="En 7.56 : plafond de gains de 900 par semaine, stock maximum de 2 000. Dépenser du stock ne restaure jamais le plafond de gains.", Minutes=25, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Weekly, RequiredQuestKey="dawntrail", Priority=90, SourceUrls=[Patch756] },
        new() { Id="mnemonics-spend", Title="Examiner les échanges de mémoquartz", Description="Comparer les coûts chez le vendeur avec les pièces faibles du job actif. Aucun achat automatique ; le stock disponible ne dit pas combien a été gagné cette semaine.", Minutes=5, Focus=ObjectiveFocus.Gearing, RewardItemLevel=780, RequiredQuestKey="dawntrail", Priority=88, Repeatable=true, SourceUrls=[Patch74,Patch756] },
        new() { Id="heavyweight-normal", Title="Équipement : Heavyweight normal", Description="Entrée i745, équipement i770 via les jetons. Les jetons ordinaires sont libres en 7.56 ; la Heavy Holoblade est suivie à part.", MinimumItemLevel=745, RewardItemLevel=770, RewardSlots=[GearSlotKind.Armor,GearSlotKind.Accessory], Minutes=20, Focus=ObjectiveFocus.Gearing, UnlockKey="heavyweight-normal", RequiredQuestKey="dawntrail", Priority=80, Repeatable=true, SourceUrls=[Patch74,Patch75] },
        new() { Id="heavyweight-holoblade", Title="Récupérer la Heavy Holoblade hebdomadaire", Description="Vérifier la récompense du dernier combat Heavyweight normal. La victoire seule ne prouve pas que la récompense hebdomadaire a été obtenue.", MinimumItemLevel=745, Minutes=20, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Weekly, UnlockKey="heavyweight", RequiredQuestKey="dawntrail", Priority=87, SourceUrls=[Patch74,Patch75] },
        new() { Id="alliance-loot", Title="Windurst : pièce d'équipement hebdomadaire", Description="Entrée i755, équipement i780. Suivi du butin de l'alliance indépendant de la pièce d'échange.", MinimumItemLevel=755, RewardItemLevel=780, RewardSlots=[GearSlotKind.Armor], Minutes=45, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Weekly, UnlockKey="windurst", RequiredQuestKey="dawntrail", Priority=88, SourceUrls=[Patch75] },
        new() { Id="alliance-coin", Title="Windurst : pièce d'échange hebdomadaire", Description="Vérifier la pièce d'échange de Windurst, distincte du butin d'équipement. Un clear ou un jet de dés ne suffit pas à déduire les deux états.", MinimumItemLevel=755, Minutes=45, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Weekly, UnlockKey="windurst", RequiredQuestKey="dawntrail", Priority=86, SourceUrls=[Patch75] },
        new() { Id="unmaking-extreme", Title="Progresser sur The Unmaking (Extreme)", Description="Entrée i770 ; armes i785. Prévoir apprentissage, composition de groupe et temps de recherche en plus du temps indicatif.", MinimumItemLevel=770, RewardItemLevel=785, RewardSlots=[GearSlotKind.Weapon], Minutes=60, MinimumAmbition=PlayAmbition.Extreme, Focus=ObjectiveFocus.Gearing, UnlockKey="unmaking-extreme", RequiredQuestKey="dawntrail", Priority=74, Repeatable=true, SourceUrls=[Patch75] },
        Savage("heavyweight-savage-1", "Heavyweight Savage : premier combat",760,75),
        Savage("heavyweight-savage-2", "Heavyweight Savage : deuxième combat",765,74),
        Savage("heavyweight-savage-3", "Heavyweight Savage : troisième combat",770,73),
        Savage("heavyweight-savage-4", "Heavyweight Savage : dernier combat",770,72),
        new() { Id="relic", Title="Continuer l'arme relique de Dawntrail", Description="Vérifier l'étape courante de la relique et ses prérequis dans le journal. Les matériaux et étapes ne sont pas inférés depuis le niveau d'objet.", Minutes=30, Focus=ObjectiveFocus.Gearing, UnlockKey="relic", RequiredQuestKey="dawntrail", Priority=60, Repeatable=true, SourceUrls=[Patch755] },
        new() { Id="wondrous-tails", Title="Préparer ou rendre le carnet de Khloe", Description="Objectif facultatif. Vérifier le carnet et sa date limite en jeu ; le reset de disponibilité ne signifie pas qu'un carnet ancien a été rendu.", MinimumLevel=60, Minutes=30, Focus=ObjectiveFocus.Weekly, Cadence=ResetCadence.Weekly, UnlockKey="wondrous-tails", Priority=45, Optional=true, SourceUrls=["https://na.finalfantasyxiv.com/lodestone/topics/detail/159309cb1ef0706cf37a9a91e3e18865b70097a6"] },
    };

    private static ObjectiveDefinition Unlock(string id, string title, string unlockKey, int priority, string source)
        => new() { Id=id, Title=title, Description="Vérifier la quête d'accès dans le journal et terminer ses prérequis d'épopée. Le suivi est confirmé dès que l'accès est observé.", Minutes=20, Focus=ObjectiveFocus.Story, UnlockKey=unlockKey, RequiredQuestKey="dawntrail", Priority=priority, SourceUrls=[source] };

    private static ObjectiveDefinition Savage(string id, string title, int minimumIlvl, int priority)
        => new() { Id=id, Title=title, Description="Équipement i790, arme i795 au dernier combat ; restrictions hebdomadaires levées en 7.56. Activité répétable : la maîtrise du combat et le groupe restent nécessaires, l'iLv ne mesure pas la compétence.", MinimumItemLevel=minimumIlvl, RewardItemLevel=id.EndsWith("-4", StringComparison.Ordinal) ? 795 : 790, RewardSlots=id.EndsWith("-4", StringComparison.Ordinal) ? [GearSlotKind.Weapon] : id.EndsWith("-1", StringComparison.Ordinal) ? [GearSlotKind.Accessory] : [GearSlotKind.Armor], Minutes=90, MinimumAmbition=PlayAmbition.Savage, Focus=ObjectiveFocus.Gearing, UnlockKey=id, RequiredQuestKey="dawntrail", Priority=priority, Repeatable=true, SourceUrls=id.EndsWith("-4", StringComparison.Ordinal) ? [Patch74,Patch756,"https://na.finalfantasyxiv.com/lodestone/playguide/db/item/21e3f444139"] : [Patch74,Patch756] };
}
